# WhatATheme
# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# URL of the Site
url: 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Welcome to JunYoung's blog
# Description of the Site
description: Personal portfolio/Diary
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: AI, Developer, Research engineer
# URL for the Image of custom Favicon
favicon-url: 


# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/junia3/junia3.github.io/blob/main/assets/images/wood_back.jpg?raw=true

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jun_yonsei@yonsei.ac.kr
facebook_username: jyyonsei
twitter_username: 
instagram_username: ___xoo00
linkedin_username: 
github_username:  junia3
youtube_channel_id: 
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: JY

# Name of the Author
author-name: JunYoung
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/79881119?v=4
# 60 Words About the Author
author-about: Yonsei University, Electrical electronic engineering, YAI, Artificial intelligence, Deep learning, Machine learning, Seoul, South Korea
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/junia3

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
